# This is a basic workflow to help you get started with Actions

name: Autodeploy on ankiweb.net

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Archive all repo for sending
        env:
          TARGET_ARCHIVE: /tmp/$GITHUB_SHA.zip
        run: zip -r $TARGET_ARCHIVE . -x '*.git*' '.github'

      - name: Listing
        env:
          TARGET_ARCHIVE: ${{ env.GITHUB_SHA }}
        run: echo "/temp/$TARGET_ARCHIVE.zip"
        
      - name: Uploaad to ankiweb.net
        uses: fjogeleit/http-request-action@master
        env:
          ANKI_LOGIN: ${{ secrets.ANKILOGIN }}
          ANKI_PASSWORD: ${{ secrets.ANKIPASSWORD }}  
        with:
          url: 'https://ankiweb.net/shared/upload'
          method: 'GET'
          username: $ANKI_LOGIN
          password: $ANKI_PASSWORD
          data: >-
            { 
            "title": "Cambridge Dictionary",
            'tags' : 'cambridge, addon, wordlists',
            'supportURL' : 'https://github.com/am-silex/anki_cambridge',
            'minVer0' : '0',
            'maxVer0' : '0',
            'desc' : 'Test desc - to be replaced',
            'id' : '1875288089',
            'submit' : 'Update'
            }
          files: '{ "v21file0": "$TARGET_ARCHIVE" }'

        



