# This is a basic workflow to help you get started with Actions

name: Autodeploy on ankiweb.net

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: Archive all repo for sending
        run: zip -r $GITHUB_WORKSPACE/$GITHUB_SHA.zip . -x '*.git*' '.github',

      - name: Get csrf token from Anki
        id: authRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://ankiweb.net/account/login'
          method: 'GET'
    
      - name: Retrieve CSRF token
        run: echo ${{ steps.authRequest.outputs.response }} | grep  -oP 'csrf_token" value="\K([^"]+)' > token.txt
          
      - name: Auth with Anki
        env:
          ANKILOGIN: ${{ secrets.ANKILOGIN }}
          ANKIPASSWORD: ${{ secrets.ANKIPASSWORD }}
          
        run: |
          CSRF=$(cat token.txt)          
          curl -d 'submitted=1&csrf_token='$CSRF'&username='$ANKILOGIN'&password='$ANKIPASSWORD https://ankiweb.net/account/login -c $GITHUB_WORKSPACE/cookie -b 'ankiweb=login' > null
          echo "ANKI_COOKIE="$(cat $GITHUB_WORKSPACE/cookie | grep -oP '^#HttpOnly_ankiweb.net.+ankiweb\s+\K.+$') >> $GITHUB_ENV
        
        
      - name: Upload to anki
        run: >
          curl
          -F 'title=Cambridge Dictionary'
          -F 'tags=cambridge, addon, wordlists'
          -F 'supportURL=https://github.com/am-silex/anki_cambridge'
          -F 'minVer0=0'
          -F 'maxVer0=0'
          -F "desc=Anki Add-on for download definition and sound from Cambridge Dictionary website. What it's done (so far): Creating notes from link to a word (word title, definition, gramar, IPA, sound, meanings, examples) Fetching words from your wordlists - if you supply cookie for you account and wordlist IDs Please, follow these links for quick visual how-to guide. https://ibb.co/94cq40m https://ibb.co/WBzw37R Anyone willing to improve my idea and contribute is welcome on addon's git: https://github.com/am-silex/anki_cambridge"
          -F 'id=1875288089'
          -F 'submit=Update'
          -F 'file=@${{ github.workspace }}/${{ github.sha }}.zip;filename=v21file0'
          -b 'ankiweb=${{ env.ANKI_COOKIE }}'
          https://ankiweb.net/shared/upload
          
        
      
